version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tlotlo
      POSTGRES_DB: ev_charging
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ocpp-server:
    build: ./ocpp-server
    ports:
      - "8887:8887"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/ev_charging
      DB_USER: postgres
      DB_PASS: Tlotlo

  backend-api:
    build: ./backend-api
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-api

volumes:
  postgres_data: